package comp.dsd.dlms.corba.classes;


/**
* classes/DlmsServerCorbaInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Softwares/Eclipse/eclipse-workspace/DLMS/src/main/java/comp/dsd/dlms/corba/DlmsServerCorbaInterface.idl
* Thursday, February 21, 2019 2:51:53 o'clock PM EST
*/

public interface DlmsServerCorbaInterfaceOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);
  String borrowItem (String userID, String itemID, int numberOfDays);
  String joinToItemWaitList (String userID, String itemID, int numberOfDays);
  String leaveItemWaitList (String userID, String itemID);
  String findItem (String userID, String itemName);
  String returnItem (String userID, String itemID);
  String exchangeItem (String userID, String newItemID, String oldItemID);
  void shutDown ();
} // interface DlmsServerCorbaInterfaceOperations
