package comp.dsd.dlms.corba.classes;

/**
* classes/DlmsServerCorbaInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Softwares/Eclipse/eclipse-workspace/DLMS/src/main/java/comp/dsd/dlms/corba/DlmsServerCorbaInterface.idl
* Thursday, February 21, 2019 2:51:53 o'clock PM EST
*/

public final class DlmsServerCorbaInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface value = null;

  public DlmsServerCorbaInterfaceHolder ()
  {
  }

  public DlmsServerCorbaInterfaceHolder (comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comp.dsd.dlms.corba.classes.DlmsServerCorbaInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comp.dsd.dlms.corba.classes.DlmsServerCorbaInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comp.dsd.dlms.corba.classes.DlmsServerCorbaInterfaceHelper.type ();
  }

}
