package comp.dsd.dlms.corba.classes;


/**
* classes/DlmsServerCorbaInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Softwares/Eclipse/eclipse-workspace/DLMS/src/main/java/comp/dsd/dlms/corba/DlmsServerCorbaInterface.idl
* Thursday, February 21, 2019 2:51:53 o'clock PM EST
*/

public interface DlmsServerCorbaInterface extends DlmsServerCorbaInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DlmsServerCorbaInterface
