package comp.dsd.dlms.corba.classes;


/**
* classes/DlmsServerCorbaInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Softwares/Eclipse/eclipse-workspace/DLMS/src/main/java/comp/dsd/dlms/corba/DlmsServerCorbaInterface.idl
* Thursday, February 21, 2019 2:51:53 o'clock PM EST
*/

public abstract class DlmsServerCorbaInterfacePOA extends org.omg.PortableServer.Servant
 implements comp.dsd.dlms.corba.classes.DlmsServerCorbaInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("removeItem", new java.lang.Integer (1));
    _methods.put ("listItemAvailability", new java.lang.Integer (2));
    _methods.put ("borrowItem", new java.lang.Integer (3));
    _methods.put ("joinToItemWaitList", new java.lang.Integer (4));
    _methods.put ("leaveItemWaitList", new java.lang.Integer (5));
    _methods.put ("findItem", new java.lang.Integer (6));
    _methods.put ("returnItem", new java.lang.Integer (7));
    _methods.put ("exchangeItem", new java.lang.Integer (8));
    _methods.put ("shutDown", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // classes/DlmsServerCorbaInterface/addItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.addItem (managerID, itemID, itemName, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // classes/DlmsServerCorbaInterface/removeItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.removeItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // classes/DlmsServerCorbaInterface/listItemAvailability
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listItemAvailability (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // classes/DlmsServerCorbaInterface/borrowItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         int numberOfDays = in.read_long ();
         String $result = null;
         $result = this.borrowItem (userID, itemID, numberOfDays);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // classes/DlmsServerCorbaInterface/joinToItemWaitList
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         int numberOfDays = in.read_long ();
         String $result = null;
         $result = this.joinToItemWaitList (userID, itemID, numberOfDays);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // classes/DlmsServerCorbaInterface/leaveItemWaitList
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.leaveItemWaitList (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // classes/DlmsServerCorbaInterface/findItem
       {
         String userID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (userID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // classes/DlmsServerCorbaInterface/returnItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.returnItem (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // classes/DlmsServerCorbaInterface/exchangeItem
       {
         String userID = in.read_string ();
         String newItemID = in.read_string ();
         String oldItemID = in.read_string ();
         String $result = null;
         $result = this.exchangeItem (userID, newItemID, oldItemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // classes/DlmsServerCorbaInterface/shutDown
       {
         this.shutDown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:classes/DlmsServerCorbaInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DlmsServerCorbaInterface _this() 
  {
    return DlmsServerCorbaInterfaceHelper.narrow(
    super._this_object());
  }

  public DlmsServerCorbaInterface _this(org.omg.CORBA.ORB orb) 
  {
    return DlmsServerCorbaInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class DlmsServerCorbaInterfacePOA
