package comp.dsd.dlms.corba.classes;


/**
* classes/DlmsServerCorbaInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Softwares/Eclipse/eclipse-workspace/DLMS/src/main/java/comp/dsd/dlms/corba/DlmsServerCorbaInterface.idl
* Thursday, February 21, 2019 2:51:53 o'clock PM EST
*/

abstract public class DlmsServerCorbaInterfaceHelper
{
  private static String  _id = "IDL:classes/DlmsServerCorbaInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (comp.dsd.dlms.corba.classes.DlmsServerCorbaInterfaceHelper.id (), "DlmsServerCorbaInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DlmsServerCorbaInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface)
      return (comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      comp.dsd.dlms.corba.classes._DlmsServerCorbaInterfaceStub stub = new comp.dsd.dlms.corba.classes._DlmsServerCorbaInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface)
      return (comp.dsd.dlms.corba.classes.DlmsServerCorbaInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      comp.dsd.dlms.corba.classes._DlmsServerCorbaInterfaceStub stub = new comp.dsd.dlms.corba.classes._DlmsServerCorbaInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
